### ISSUE TITLE
Does not work on Safari correctly

### ISSUE THREAD

**Issue by Franciscojose05** [tony-xlh/image-cropper-component#1]
Hi, thanks for your Repo. It ist quite helpful. I have testet your Demo on different Browsers. The cropping function does not work on Safari correctly. 
Error: After cropping the image, i don't see the cropped Image.

**Comment by tony-xlh** [comment]
This is not related to Safari. It should be the license's problem. If the license for Dynamsoft Document Normalizer expires, you cannot get the cropped image. Apply for a license [here](https://www.dynamsoft.com/customer/license/trialLicense?product=ddn) or disable it so that it just uses canvas to get the cropped rectangle.
